src/apps/docs/urls.py
"""Patrones de ruta de documentos."""
# pylint: disable=W0613,R0201,R0903

from django.urls import path
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from apps.docs import views
from apps.docs.views import (
    IndexLMD,
    DocDetail,
    ProcesoList,
    Buscador,
    SetupDoc,
    ProcessAdd,
    TipoAdd,
    DocAdd,
    RevisionAdd,
    Reportes,
    PanicButtonView,
    ReportesList,
    PanicResolve,
    IndexLDP,
    IndexLDT,
    IndexLDR,
    NotificacionListView,
    NotificacionDetailView,
)

app_name = "docs"
urlpatterns = [
    path("", IndexLMD.as_view(), name="index"),
    path("panic/<int:pk>", PanicButtonView.as_view(), name="panic"),
    path(
        "panic_success/",
        TemplateView.as_view(template_name="docs/panic_success.html"),
        name="panic_success",
    ),
    path("panic_reports", ReportesList.as_view(), name="panic_reportes"),
    path("panic_resolve/<int:pk>", PanicResolve.as_view(), name="panic_resolve"),
    path("<int:pk>/detalle", DocDetail.as_view(), name="detalle"),
    path("proceso/<slug:slug>", ProcesoList.as_view(), name="proceso"),
    path("buscador/", Buscador.as_view(), name="buscador"),
    path("reportes/", Reportes.as_view(), name="reportes"),
    path("add/", DocAdd.as_view(), name="add"),
    path("setup/", login_required(SetupDoc.as_view()), name="setup"),
    path("process_add/", login_required(ProcessAdd.as_view()), name="process_add"),
    path("tipo_add/", login_required(TipoAdd.as_view()), name="tipo_add"),
    path("ldp/", IndexLDP.as_view(), name="ldp"),
    path("ldt/", IndexLDT.as_view(), name="ldt"),
    path("ldr/", IndexLDR.as_view(), name="ldr"),
    path("<int:pk>/add", RevisionAdd.as_view(), name="rev_add"),
    path(
        "notificaciones/",
        login_required(NotificacionListView.as_view()),
        name="notificaciones_list",
    ),
    path(
        "notificaciones/<int:pk>/",
        login_required(NotificacionDetailView.as_view()),
        name="notificaciones_detail",
    ),
    path(
        "get_notification_recipients_count/",
        views.get_notification_recipients_count,
        name="get_notification_recipients_count",
    ),
    path("cmi-movil/ayuda/", views.CMIMovilView.as_view(), name="cmi_movil_help"),
]

src/apps/ideas/urls.py
from django.urls import path
from .views import IdeasIndex, IdeaDetail, IdeaAdd

app_name = 'ideas'
urlpatterns = [
    path('', IdeasIndex.as_view(), name='index'),
    path('add/', IdeaAdd.as_view(), name='add'),
    path('detalle/<int:pk>/', IdeaDetail.as_view(), name='detalle')
]

src/apps/pas/urls.py
from django.urls import path

from .views import (
    PASIndex,
    PASAdd,
    PASDetail,
    PlanSummaryView,
    PlanActivitiesView,
    PlanUpdateView,
    PlanClosureView,
    ActivityCreateView,
    ActivityUpdateView,
    ActivityDeleteView,
    FollowUpCreateView,
    FollowUpListView,
)

app_name = 'pas'

urlpatterns = [
    path('', PASIndex.as_view(), name='index'),
    path('add/', PASAdd.as_view(), name='add'),
    path('detalle/<int:pk>/', PASDetail.as_view(), name='detalle'),
    path('<int:pk>/summary/', PlanSummaryView.as_view(), name='plan-summary'),
    path('<int:pk>/activities/', PlanActivitiesView.as_view(), name='plan-activities'),
    path('<int:pk>/edit/', PlanUpdateView.as_view(), name='plan-edit'),
    path('<int:pk>/closure/', PlanClosureView.as_view(), name='plan-closure'),
    path('<int:pk>/activities/add/', ActivityCreateView.as_view(), name='activity-add'),
    path('activities/<int:pk>/edit/', ActivityUpdateView.as_view(), name='activity-edit'),
    path('activities/<int:pk>/delete/', ActivityDeleteView.as_view(), name='activity-delete'),
    path('activities/<int:pk>/followups/', FollowUpListView.as_view(), name='followup-list'),
    path('activities/<int:pk>/followups/add/', FollowUpCreateView.as_view(), name='followup-add'),
]

src/core/urls.py
"""Patrones de rutas generales."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from core.views import Index


urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(template_name="logout.html"), name="logout"),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("docs/", include("apps.docs.urls")),
    path("carto/", include("apps.carto.urls")),
    path("ideas/", include("apps.ideas.urls")),
    path("pas/", include("apps.pas.urls")),
    path("vozmac/", include("apps.vozmac.urls")),
    path("profiles/", include("apps.profiles.urls")),
    path("pmml/", include("apps.pmml.urls")),
    path("api/v1/vozmac/", include("apps.vozmac.api.urls")),
    path("api/v1/pas/", include("apps.pas.api.urls")),
    path("api/v1/docs/", include("apps.docs.api.urls")),
    path("api/v1/ideas/", include("apps.ideas.api.urls")),
    path("api/v1/profiles/", include("apps.profiles.api.urls")),
    path("", Index.as_view(), name="index"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/templates/partials/_footer.html
{% load static %}
<footer class="navbar bg-secondary" style="margin-top: 20px;">
  <div class="container-fluid">
    <a class="navbar-brand text-primary" href="#">SCG Tlaxcala &copy; 2023</a>
    {% if panicButton %}
    <div class="d-flex justify-content-end">
      <a 
        type="button" 
        class="btn btn-primary btn-lg iframe"  
        href="{% url 'docs:panic' pk=831 %}">
        Notificar documento faltante
      </a>
    </div>
    {% endif %}
  </div>
</footer>

src/apps/templates/partials/_freshdesk.html
<script type='text/javascript' src='https://widget.freshworks.com/widgets/6000000705.js' async defer></script>

src/apps/templates/partials/_messages.html
<div class="row">
  <div class="col">
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message | safe }}
      </div>
    {% endfor %}
  </div>
</div>

src/apps/templates/partials/_meta.html
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Cuadro de Mando Integral">
<meta name="author" content="Javier Sanchez Toledano <javier.sanchezt@ine.mx>">
<link rel="icon" href="https://www.ine.mx/wp-content/uploads/2017/03/favicon.png" sizes="32x32" />
<link rel="icon" href="https://www.ine.mx/wp-content/uploads/2017/03/favicon.png" sizes="192x192" />
<link rel="apple-touch-icon" href="https://www.ine.mx/wp-content/uploads/2017/03/favicon.png" />
<meta name="msapplication-TileImage" content="https://www.ine.mx/wp-content/uploads/2017/03/favicon.png" />

src/apps/templates/partials/_navbar.html
{% load static %}
{% load docs_tags %}

<nav class="navbar bg-primary navbar-expand-lg" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">SGC Tlaxcala</a>
    <button class="navbar-toggler"
            type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'index' %}"><i class="fa fa-home" aria-hidden="true"></i> Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'docs:index' %}"><i class="fa fa-file-text-o" aria-hidden="true"></i> Documentación</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pas:index' %}"><i class="fa fa-bug" aria-hidden="true"></i> Planes</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'ideas:index' %}" class="nav-link"><i class="fa fa-lightbulb-o" aria-hidden="true"></i> Caja de Ideas</a>
        </li>
      </ul>
      <form class="d-flex" role="search"  method="get" action="{% url 'docs:buscador' %}">
        <input class="form-control me-2" type="search" placeholder="Escribe aquí" name="q" aria-label="Buscar">
        <button class="btn btn-secondary" type="submit">Buscar</button>
      </form>

      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa fa-user"></i>&nbsp; {{ request.user.first_name }} {{ request.user.last_name }}
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="dropdown-item pr-2" style="background: none; border: none; padding-left: 2; cursor: pointer;">Cerrar sesión</button>
              </form>
            </li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
        </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>

{% if panic_reports > 0 %}
<div style="margin: 10px 50px 10px">
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>¡Alerta!</strong> Hay {{ panic_reports }} reportes de documentos sin atender. <a href="{% url 'docs:panic_reportes' %}" class="alert-link">Ver reportes</a>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
</div>
{% endif %}

src/apps/templates/partials/_scripts.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

<script>
	window.fwSettings={
    'widget_id':6000000705,
    'locale': 'es-LA'
	};
	!function(){if("function"!=typeof window.FreshworksWidget){var n=function(){n.q.push(arguments)};n.q=[],window.FreshworksWidget=n}}()
</script>

src/apps/templates/partials/_styles.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/css/fork-awesome.min.css" integrity="sha256-XoaMnoYC5TH6/+ihMEnospgm0J1PM/nioxbOUdnM8HY=" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/cmi_styles.css' %}" />